src/ExpressiveAnnotations.MvcWebSample/Controllers/SystemController.cs
using System.Web.Mvc;
using ExpressiveAnnotations.MvcWebSample.Misc;

namespace ExpressiveAnnotations.MvcWebSample.Controllers
{
    public class SystemController : Controller
    {
        public ActionResult SetCulture(string lang, string returnUrl)
        {
            CultureManager.Instance.Save(lang, HttpContext);
            return Redirect(returnUrl);
        }

        public ActionResult SetValidation(string type, string returnUrl)
        {
            ValidationManager.Instance.Save(type, HttpContext);
            return Redirect(returnUrl);
        }

        public ActionResult SetIndication(string value, string returnUrl)
        {
            IndicationsManager.Instance.Save(value, HttpContext);
            return Redirect(returnUrl);
        }

        [HttpPost]
        public JsonResult SetTriggers(string events)
        {
            TriggersManager.Instance.Save(events, HttpContext);
            return Json(new {success = true});
        }

        [HttpPost]
        public JsonResult SetVerbosity(bool value)
        {
            VerbosityManager.Instance.Save(value, HttpContext);
            return Json(new {success = true});
        }
    }
}

src/ExpressiveAnnotations.MvcWebSample/Views/Shared/_Culture.cshtml
@using System.Threading

@{
    var plLabel = "pl".Equals(Thread.CurrentThread.CurrentUICulture.TwoLetterISOLanguageName) ? "[polski]" : "polski";
    var enLabel = "en".Equals(Thread.CurrentThread.CurrentUICulture.TwoLetterISOLanguageName) ? "[english]" : "english";
}
<div>
    change language to test localized information:
    <a href="@Url.Action("SetCulture", "System", new {lang = "pl", returnUrl = Request.RawUrl}, null)">@plLabel</a>
    <a href="@Url.Action("SetCulture", "System", new {lang = "en", returnUrl = Request.RawUrl}, null)">@enLabel</a>
</div>

src/ExpressiveAnnotations.MvcWebSample/Views/Shared/_EAOptions.cshtml
@if ("client".Equals(ViewBag.Validation))
{
    <div id="triggers">
        <a href="https://github.com/jwaliszko/ExpressiveAnnotations#how-to-control-frequency-of-dependent-fields-validation">set dependency validation triggers</a>:
        <input type="checkbox" id="changeTrigger" name="changeTrigger" data-val="change" @(ViewBag.Triggers.Contains("change") ? Html.Raw("checked=\"checked\"") : Html.Raw(""))/> change
        <input type="checkbox" id="pasteTrigger" name="pasteTrigger" data-val="afterpaste" @(ViewBag.Triggers.Contains("afterpaste") ? Html.Raw("checked=\"checked\"") : Html.Raw(""))/> paste
        <input type="checkbox" id="keyupTrigger" name="keyupTrigger" data-val="keyup" @(ViewBag.Triggers.Contains("keyup") ? Html.Raw("checked=\"checked\"") : Html.Raw(""))/> keyup
    </div>
    <div id="debug">
        <a href="https://github.com/jwaliszko/ExpressiveAnnotations#can-i-increase-web-console-verbosity-for-debug-purposes">set verbose output for web console</a>:
        <input type="checkbox" id="debugFlag" name="debugFlag" data-val="change" @(ViewBag.Verbose ? Html.Raw("checked=\"checked\"") : Html.Raw(""))/>
    </div>
}

src/ExpressiveAnnotations.MvcWebSample/Views/Shared/_Indications.cshtml
@if ("client".Equals(ViewBag.Validation))
{
    var asterisksLabel = "asterisks".Equals(ViewBag.Indication) ? "[asterisks]" : "asterisks";
    var asterisksWithHidingLabel = "asterisks-with-hiding".Equals(ViewBag.Indication) ? "[asterisks-with-hiding]" : "asterisks-with-hiding";
    var noAnnotatingLabel = "no-annotating".Equals(ViewBag.Indication) ? "[no-annotating]" : "no-annotating";
     
    <div>
        annotate required fields using:
        <a href="@Url.Action("SetIndication", "System", new {value = "asterisks", returnUrl = Request.RawUrl}, null)">@asterisksLabel</a>
        <a href="@Url.Action("SetIndication", "System", new {value = "asterisks-with-hiding", returnUrl = Request.RawUrl}, null)">@asterisksWithHidingLabel</a>
        <a href="@Url.Action("SetIndication", "System", new {value = "no-annotating", returnUrl = Request.RawUrl}, null)">@noAnnotatingLabel</a>
    </div>
}

src/ExpressiveAnnotations.MvcWebSample/Views/Shared/_Layout.cshtml
@using System.Threading
<!DOCTYPE html>

@{
    var lang = Thread.CurrentThread.CurrentCulture.TwoLetterISOLanguageName;
    var browser = Request.Browser.Browser.ToLowerInvariant();
}

<html lang="@lang">
    <head>
        <meta charset="utf-8" />
        <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1" />
        <meta name="author" content="Jarosław Waliszko, https://github.com/jwaliszko/ExpressiveAnnotations" />
        <meta name="copyright" content="Copyright (c) 2014 Jarosław Waliszko" />
        <meta name="postbacks" content="@Session["Postbacks"]" /> @*counter for ui tests*@

        <link rel="shortcut icon" type="image/ico" href="~/favicon.ico" />
        <title>ExpressiveAnnotations</title>
        @Styles.Render("~/Content/css")
        @Styles.Render("~/Content/themes/base/css")
    </head>
    <body class="@browser">
        <div id="body">
            <section class="content-wrapper">
                @RenderBody()
            </section>
        </div>

        @Scripts.Render("~/bundles/jquery")
        @Scripts.Render("~/bundles/jqueryui")
        @RenderSection("scripts", required: false)
    </body>
</html>

src/ExpressiveAnnotations.MvcWebSample/Views/Shared/_Validation.cshtml
@{
    var clientLabel = "client".Equals(ViewBag.Validation) ? "[client]" : "client";
    var serverLabel = "server".Equals(ViewBag.Validation) ? "[server]" : "server";
}
<div>
    disable or enable client-side validation:
    <a href="@Url.Action("SetValidation", "System", new {type = "client", returnUrl = Request.RawUrl}, null)">@clientLabel</a>
    <a href="@Url.Action("SetValidation", "System", new {type = "server", returnUrl = Request.RawUrl}, null)">@serverLabel</a>
</div>